### Create a new Stripe Checkout Session - One-time payment with customer
POST http://localhost:3000/checkout-session
content-type: application/json

{
  "priceId": "price_1NSljBLNWtF9dCjUL5UWJyXw", 
  "customerId": "cus_OFLrxXEx8d7Uvc",
  "surveyId": "12345"
}

### Create a new Stripe Checkout Session - One-time payment without customer
POST http://localhost:3000/checkout-session
content-type: application/json

{
  "priceId": "price_1NSljBLNWtF9dCjUL5UWJyXw", 
  "email": "testcust@mail.com",
  "surveyId": "12345"
}